name: Runner Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04
    container: alpine:latest  # 진짜 깡통 이미지
    steps:
      - run: echo "hello cicd"
      - run: java --version
