name: cicd runner test 


on: 
  push: 
    branches: [main]

job: 
  test: 
    runs-on: ubuntu-22.04
    step: 
      - name: Hello CICD (예상:성공) 
        run: echo "hello cicd" 

      - name: checkout 없이 gradlew 실행 (예상:실패)
        run: ./gradlew build
